### ISSUE TITLE
Android 10 已无法获取设备序列号（Serial）

### ISSUE THREAD

**Issue by BeQuietLee** [No89757/Udid#1]
> Reference：https://stackoverflow.com/a/47022263/10827627

Android 10 进一步收紧了`Build.getSerial()`的权限，只有满足以下条件之一时才可以读取，否则会抛出`SecurityException`，对于通常手段开发的应用这几乎是不可能的

- 应用具有系统签名，且申请了`READ_PRIVILEGED_PHONE_STATE`权限
- 应用是`device or profile owner`角色且申请了`READ_PHONE_STATE`权限

作者在[漫谈设备唯一ID](https://www.jianshu.com/p/df3f549ddd35)一文中对“设备序列号”的描述有误，烦请确认~

@No89757

**Comment by BillyWei01** [comment]
已修正，多谢反馈。
